#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/config/functions"

auth-command() {
  declare desc="Authorize litestream to a remote storage, e.g. S3"
  local cmd="$PLUGIN_COMMAND_PREFIX:auth" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  dokku_log_info2_quiet "Authorizing litestream for replica location"

  read -e -p "Enter your ACCESS_KEY_ID:    " ACCESS_KEY_ID
  read -e -p "Enter you SECRET_ACCESS_KEY: " SECRET_ACCESS_KEY

  dokku_log_verbose_quiet "Saving credentials"

  mkdir $LITESTREAM_CREDENTIALS_ROOT

  echo $ACCESS_KEY_ID > $LITESTREAM_CREDENTIALS_ACCESS_KEY_ID
  echo $SECRET_ACCESS_KEY > $LITESTREAM_CREDENTIALS_SECRET_ACCESS_KEY

  dokku_log_verbose_quiet "Credentials saved"
}

auth-command "$@"
