#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/config/functions"

destroy-command() {
  declare desc="Destroy litestream container for the application"
  local cmd="$PLUGIN_COMMAND_PREFIX:destroy" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP_NAME="$1"

  # TODO:
  # - validate APP_NAME

  local SERVICE_NAME="dokku.$PLUGIN_COMMAND_PREFIX.$APP_NAME"
  local ID=$(docker ps -a --no-trunc --filter "name=^/$SERVICE_NAME$" --format '{{ .ID }}') || true
  [[ -z $ID ]] && dokku_log_warn "Service is already stopped" && return 0

  if [[ -n $ID ]]; then
    dokku_log_info2_quiet "Removing litestream container"
    docker rm --force "$SERVICE_NAME" >/dev/null
    dokku_log_verbose_quiet "Container removed"
  else
    dokku_log_verbose_quiet "No container exists for $APP_NAME"
  fi
}

destroy-command "$@"
