#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/config/functions"

start-command() {
  declare desc="Start litestream container for the application"
  local cmd="$PLUGIN_COMMAND_PREFIX:start" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP_NAME="$1"

  # TODO:
  # - validate APP_NAME

  local SERVICE_NAME="dokku.$PLUGIN_COMMAND_PREFIX.$APP_NAME"

  dokku_log_info2_quiet "Starting litestream container"
  docker start "$SERVICE_NAME"
  dokku_log_verbose_quiet "Started container for $APP_NAME"
}

start-command "$@"
